### PR TITLE
Lps 186854  add log

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi Summer@zhangyan0701, 

We have a request regarding the CI testing results. Could you please assist me in scanning the test logs to find any occurrences of the following BLOCKING content?

Please let me know if you need any further information. Thanks!

```
_log.warn(
    StringBundler.concat(
        "BLOCKING:", className, ".", _field.getName()));
```
cc @W2jx @dantewang @yuhai

**Comment by dantewang** [comment]
@zhangyan0701 Since it's warn log, it should fail the CI log assert.

**Comment by zhangyan0701** [comment]
Hi @dantewang @JanisZhang 

There is a BLOCKING warning message:
`    [junit] 2023-06-09 03:51:09.284 WARN  [liferay/document_library_raw_metadata_processor-2][ServiceProxyFactory:237] BLOCKING:com.liferay.dynamic.data.mapping.kernel.DDMStructureManagerUtil._ddmStructureManager`

Example:
[PortalLogAssertorTest-modules-integration-mysql57-jdk8/4/9](https://testray.liferay.com/home/-/testray/case_results/2345330232)
Full console:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-26/test-portal-acceptance-pullrequest(master)/9726/modules-integration-mysql57-jdk8/4/9/jenkins-console.txt.gz?authuser=0

**Comment by JanisZhang** [comment]
Thanks Summer!!!

We kindly seek assistance in identifying _all_ blocking warning messages, as it will greatly aid our current task of converting them to non-blocking operations. We kindly ask for your support or any suggested methods that would allow us to conveniently access the complete console output for easier detection.

@zhangyan0701

**Comment by JanisZhang** [comment]
Hi Summer,

Thank you so much for your assistance! 

I just wanted to let you know that I've submitted a new pull request https://github.com/JanisZhang/liferay-portal/pull/226 with the log level set to ERROR, and I've also executed the `ci:test` tests. I would greatly appreciate it if you could assist me in verifying the results once the testing process is completed.

Thanks! @zhangyan0701

**Comment by zhangyan0701** [comment]
Hi @JanisZhang 

No problem. I will check the results once they come out.

**Pull request closed without merging**
