### PR TITLE
Test Blocking

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
Hi Summer @zhangyan0701,

Happy Friday!
As we previously did in https://github.com/JanisZhang/liferay-portal/pull/226, we need to retest the blocking field. 

In addition to the previous testing, we would also like to examine the exception stack trace. I've included code to print the exception, which should be visible following the blocking message. I've already executed _**ci:test:startup**_ multiple times. 

Could you kindly assist in reviewing this once the tests have concluded? Please feel free to reach out if you have any questions. Your help is greatly appreciated!

Thanks.
Janis.

/cc @dantewang

**Comment by zhangyan0701** [comment]
Hi @JanisZhang 

I checked all the result here. There are two BLOCKING messages:
`BLOCKING:com.liferay.dynamic.data.mapping.kernel.DDMStructureManagerUtil._ddmStructureManager`
and 
`BLOCKING:com.liferay.portal.service.impl.ImageLocalServiceImpl._store`

**Comment by JanisZhang** [comment]
I found below exception trace. https://gist.github.com/JanisZhang/7126fb97b4f3e2e8e4384cef0df79f2f
cc @dantewang @zhangyan0701

**Comment by JanisZhang** [comment]
I'm checking the invoke chain, trying to find out whether we have any chance to avoid blocking...

**Comment by JanisZhang** [comment]
Force-pushed and re-run test, as ImageLocalServiceImpl has been refactored.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
Hi Summer, Could you please help to list the blocking field and its exception stack trace once the test finished? Thanks! @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
@JanisZhang 

There is one Blocking message:
```
[beanshell] 2023-08-30 11:20:47.470 ERROR [SCR Component Actor][ServiceProxyFactory:226] BLOCKING:com.liferay.portal.service.impl.ImageLocalServiceImpl._store
[beanshell] 2023-08-30 11:20:47.472 ERROR [SCR Component Actor][ServiceProxyFactory:232] Exception stack trace:
[beanshell] java.lang.Exception: BLOCKING
[beanshell] 	at com.liferay.portal.kernel.util.ServiceProxyFactory$AwaitServiceInvocationHandler.invoke(ServiceProxyFactory.java:230) ~[portal-kernel.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy111.hasFile(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.ImageLocalServiceImpl.updateImage(ImageLocalServiceImpl.java:262) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.ImageLocalServiceImpl.updateImage(ImageLocalServiceImpl.java:221) ~[portal-impl.jar:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[beanshell] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy112.updateImage(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.service.ImageLocalServiceUtil.updateImage(ImageLocalServiceUtil.java:368) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.util.PortalImpl.updateImageId(PortalImpl.java:6918) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.util.PortalUtil.updateImageId(PortalUtil.java:1975) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutSetLocalServiceImpl.updateLogo(LayoutSetLocalServiceImpl.java:336) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutSetLocalServiceImpl.updateLogo(LayoutSetLocalServiceImpl.java:393) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutSetLocalServiceImpl.updateLogo(LayoutSetLocalServiceImpl.java:375) ~[portal-impl.jar:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[beanshell] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[beanshell] 	at com.liferay.staging.internal.service.LayoutSetLocalServiceStagingAdvice$LayoutSetLocalServiceStagingInvocationHandler.invoke(LayoutSetLocalServiceStagingAdvice.java:126) ~[?:?]
[beanshell] 	at com.sun.proxy.$Proxy325.updateLogo(Unknown Source) ~[?:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[beanshell] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[beanshell] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy125.updateLogo(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.properties.swapper.internal.SwapDefaultGuestGroupLogoPortalInstanceLifecycleListener.portalInstanceRegistered(SwapDefaultGuestGroupLogoPortalInstanceLifecycleListener.java:69) ~[?:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$registerCompany$1(PortalInstanceLifecycleListenerManagerImpl.java:190) ~[?:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl._runIfNeeded(PortalInstanceLifecycleListenerManagerImpl.java:295) ~[?:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:174) ~[?:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$null$1(PortalInstanceLifecycleListenerManagerImpl.java:421) ~[?:?]
[beanshell] 	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:27) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:30) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:19) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$addingService$2(PortalInstanceLifecycleListenerManagerImpl.java:414) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:486) [portal-impl.jar:?]
[beanshell] 	at jdk.internal.reflect.GeneratedMethodAccessor592.invoke(Unknown Source) ~[?:?]
[beanshell] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) [portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy89.forEachCompany(Unknown Source) [?:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:411) [bundleFile:?]
[beanshell] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:368) [bundleFile:?]
[beanshell] 	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerListImpl.java:155) [com.liferay.osgi.service.tracker.collections.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:902) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:800) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:125) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:224) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:962) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$1.run(AbstractComponentManager.java:456) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:113) [bundleFile:?]
[beanshell] 	at java.lang.Thread.run(Thread.java:834) [?:?]
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2995/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0

**Comment by JanisZhang** [comment]
Thanks Summer！ @zhangyan0701

**Pull request closed without merging**
