### PR TITLE
Test blocking

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
@JanisZhang 

The functional tests didn't fail with the error message as we expected. I made a change in test.properties and re-run tests in https://github.com/zhangyan0701/liferay-portal/pull/520.

**Comment by JanisZhang** [comment]
thanks! @zhangyan0701

**Comment by zhangyan0701** [comment]
Hi @JanisZhang 

I have checked the results in https://github.com/zhangyan0701/liferay-portal/pull/520.

There is still only one Blocking message `BLOCKING:com.liferay.dynamic.data.mapping.kernel.DDMStructureManagerUtil._ddmStructureManager`. I didn't see any other class trigger this error.

**Comment by dantewang** [comment]
Thanks @zhangyan0701!

**Comment by dantewang** [comment]
@JanisZhang Please mark that one, thanks!

**Pull request closed without merging**
